// export const CarouselRequestsConstants = {
//     SET_POPULAR_GAMES: "CAROUSEL_SET_POPULAR_GAMES",
//     ADD_POPULAR_GAME_DATA: "CAROUSEL_ADD_POPULAR_GAME_DATA",
//     POPULAR_GAMES_COMPLETE: "CAROUSEL_POPULAR_GAMES_COMPLETE",
//     STORE_GENRES: "CAROUSEL_STORE_GENRES",
// };