export const filtersConstants = {
    GET_GENRES: "FILTERS_GET_GENRES",
    GET_MODES: "FILTERS_GET_MODES",
    GET_PERSPECTIVE: "FILTERS_GET_PERSPECTIVE",
    SET_TEXTFIELDS_SEARCH_RES: "FILTERS_SET_TEXTFIELDS_SEARCH_RES",
    TEXTFIELDS_RES_REQUEST: "FILTERS_TEXTFIELDS_RES_REQUEST",
    SET_SEARCH_RESULTS: "FILTERS_SEARCH_RESULTS",
    SET_CORRECT_IDS: "FILTERS_SET_CORRECT_IDS",
    SET_REACH_BOTTOM: "FILTERS_SET_REACH_BOTTOM",
    MORE_SEARCH_RESULTS: "FILTERS_MORE_SEARCH_RESULTS",
    SET_OFFSET: "FILTERS_SET_OFFSET",
    SET_REACH_END: "FILTERS_SET_REACH_END",
    SET_FILTERS: "FILTERS_SET_FILTERS",
    SET_IS_REQUEST: "FILTERS_SET_IS_REQUEST",
    SET_IS_FILTERS_LOADED: "FILTERS_SET_IS_FILTERS_LOADED",
    SET_LAST_REQUEST_FILTERS: "FILTERS_SET_LAST_REQUEST_FILTERS",
    SET_URL: "FILTERS_SET_URL",
    SET_LINK_FILTERS: "FILTERS_SET_LINK_FILTERS"
}