export const filtersConstants = {
    GET_GENRES: "FILTERS_GET_GENRES",
    GET_MODES: "FILTERS_GET_MODES",
    GET_PERSPECTIVE: "FILTERS_GET_PERSPECTIVE",
    SET_TEXTFIELDS_SEARCH_RES: "FILTERS_SET_TEXTFIELDS_SEARCH_RES",
    TEXTFIELDS_RES_REQUEST: "FILTERS_TEXTFIELDS_RES_REQUEST",
    SET_SEARCH_RESULTS: "FILTERS_SEARCH_RESULTS"
}