export const homePageRequestsConstants = {
    SET_POPULAR_GAMES: "HOMEPAGE_SET_POPULAR_GAMES",
    SET_RECENTLY_RELEASED_GAMES: "HOMEPAGE_SET_RECENTLY_RELEASED_GAMES",
    SET_COMING_SOON_GAMES: "HOMEPAGE_SET_COMING_SOON_GAMES",
}

export const bestRatedGames = {
    THIS_MONTH: "BEST_RATED_GAMES_THIS_MONTH",
    LAST_6_MONTHS: "BEST_RATED_GAMES_lAST_6_MONTHS",
    THIS_YEAR: "BEST_RATED_GAMES_THIS_YEAR",
    ALL_TIME: "BEST_RATED_GAMES_ALL_TIME"
}