export const homePageRequestsConstants = {
    SET_POPULAR_GAMES: "HOMEPAGE_SET_POPULAR_GAMES",
    SET_RECENTLY_RELEASED_GAMES: "HOMEPAGE_SET_RECENTLY_RELEASED_GAMES",
    SET_COMING_SOON_GAMES: "HOMEPAGE_SET_COMING_SOON_GAMES"
}