export const homePageRequestsConstants = {
    SET_POPULAR_GAMES: "HOMEPAGE_SET_POPULAR_GAMES",
    ADD_POPULAR_GAME_DATA: "HOMEPAGE_ADD_POPULAR_GAME_DATA",
    POPULAR_GAMES_COMPLETE: "HOMEPAGE_POPULAR_GAMES_COMPLETE",
    STORE_GENRES: "HOMEPAGE_STORE_GENRES",
};