export const RecentlyReleasedConstants = {
    ADD_RECENT_GAME: "RECENTLY_RELEASED_ADD_GAME",
    RECENTLY_RELEASED_IS_REQUEST: "RECENTLY_RELEASED_IS_REQUEST",
    RECENTLY_RELEASED_SET_TOTAL_GAMES : "RECENTLY_RELEASED_SET_TOTAL_GAMES"
};