export const uiConstants = {
    ROUTE_INDEX_STATE: "ROUTE_INDEX_STATE",
    FILTERS_CORRECT_IDS: "FILTERS_CORRECT_IDS",
    SET_ACTIVATED_FILTERS: "FILTERS_SET_ACTIVATED_FILTERS",
    SET_IS_NEED_REQUEST: "FILTERS_SET_IS_NEED_REQUEST",
}

export const RouteIndex = {
    HOMEPAGE: 0,
    SEARCH: 1,
    REVIEWS: 2
}